spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR EMAIL
    password: YOUR PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
application:
  error:
    text:
      action-failed: Action failed
  file:
    saved-file-address: src/main/java/com/selfproject/savedFile.txt